name: Publish Kaggle Notebook

on:
  push:
    branches:
      - main
    paths:
      - notebooks/train.ipynb
      - notebooks/train_experiments.ipynb

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Push train notebook
        run: kaggle kernels push -p notebooks/train

      - name: Push experiments notebook
        run: kaggle kernels push -p notebooks/train_experiments