name: Publish Kaggle Notebook

on:
  push:
    branches:
      - main
    paths:
      - notebooks/train/**
      - notebooks/train_experiments/**
      - .dvc/**
      - dataset.dvc

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v47

      ####################################################################
      # TRAIN NOTEBOOK
      ####################################################################

      - name: Prepare train package
        if: contains(steps.changed.outputs.all_changed_files, 'notebooks/train/') || contains(steps.changed.outputs.all_changed_files, '.dvc/') || contains(steps.changed.outputs.all_changed_files, 'dataset.dvc')
        run: |
          mkdir -p kaggle_train_package

          cp -R notebooks/train/* kaggle_train_package/

          mkdir -p kaggle_train_package/.dvc

          cp .dvc/config kaggle_train_package/.dvc/
          cp dataset.dvc kaggle_train_package/

      - name: Publish train notebook
        if: contains(steps.changed.outputs.all_changed_files, 'notebooks/train/') || contains(steps.changed.outputs.all_changed_files, '.dvc/') || contains(steps.changed.outputs.all_changed_files, 'dataset.dvc')
        run: |
          echo "Publishing notebooks/train"
          kaggle kernels push -p kaggle_train_package

      ####################################################################
      # TRAIN EXPERIMENTS NOTEBOOK
      ####################################################################

      - name: Prepare train_experiments package
        if: contains(steps.changed.outputs.all_changed_files, 'notebooks/train_experiments/') || contains(steps.changed.outputs.all_changed_files, '.dvc/') || contains(steps.changed.outputs.all_changed_files, 'dataset.dvc')
        run: |
          mkdir -p kaggle_train_experiments_package

          cp -R notebooks/train_experiments/* kaggle_train_experiments_package/

          mkdir -p kaggle_train_experiments_package/.dvc

          cp .dvc/config kaggle_train_experiments_package/.dvc/
          cp dataset.dvc kaggle_train_experiments_package/

      - name: Publish train_experiments notebook
        if: contains(steps.changed.outputs.all_changed_files, 'notebooks/train_experiments/') || contains(steps.changed.outputs.all_changed_files, '.dvc/') || contains(steps.changed.outputs.all_changed_files, 'dataset.dvc')
        run: |
          echo "Publishing notebooks/train_experiments"
          kaggle kernels push -p kaggle_train_experiments_package